
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "3000:3000"
    command: sleep infinity
    environment:
      - MONGO_DB_NAME=library
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
    networks:
      - dbs_network

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - dbs_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./../Data:/import
    command: ["neo4j"]
    networks:
      - dbs_network

volumes:
  mongodb-data:
  neo4j_data:

networks:
  dbs_network:
    driver: bridge